# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.2"
manifest_format = "2.0"
project_hash = "9d5bd921a92c7d3457227584e2fd50fea505e39c"

[[deps.Public]]
path = "."
uuid = "c947c6f8-4499-4aba-9a07-9ad9f868b827"
version = "0.1.0"
